[package]
name = "bevy-async-task"
description = "Ergonomic abstractions to async programming in Bevy"
license = "MIT/Apache-2.0"
repository = "https://github.com/vectorgameexperts/bevy-async-task"
authors = ["Spencer C. Imbleau"]
keywords = ["gamedev", "async"]
version = "1.3.1"
edition = "2021"

[lib]

[dependencies]
tokio = { version = "1", default-features = false, features = ["sync"] }
bevy = { version = "0.13", default-features = false, features = [
  "multi-threaded",
] }
cfg-if = "1.0"
async-std = "1.12"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-compat = "0.2"

[dev-dependencies]
futures = "0.3"
futures-timer = "3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
js-sys = "0.3"
wasm-bindgen = "0.2"
